Categories:
  - System
License: GPL-3.0-only
AuthorEmail: juam+scrambled@posteo.net
SourceCode: https://gitlab.com/juanitobananas/scrambled-exif/tree/HEAD
IssueTracker: https://gitlab.com/juanitobananas/scrambled-exif/issues
Translation: https://www.transifex.com/juanitobananas/scrambled-exif/
Changelog: https://gitlab.com/juanitobananas/scrambled-exif/blob/HEAD/CHANGELOG.md
Liberapay: juanitobananas
Bitcoin: bc1qagv574q7k66nwmtef8gxmjge4ekvnjxfytxp5e

AutoName: Scrambled Exif

RepoType: git
Repo: https://gitlab.com/juanitobananas/scrambled-exif.git

Builds:
  - versionName: 1.7.3
    versionCode: 66
    commit: HEAD
    subdir: app
    submodules: true
    gradle:
      - standard
